name: deploy
on:
 workflow_dispatch:
 push:
   branches:
     - main
     
jobs:
  build:
    name: run the child pipline
    runs-on: ubuntu-latest
    steps:
     - name: run build ns
       run: |
         echo "Build the API from child"
         echo ${{ github.event.inputs.SP_USERNAME }}
         echo ${{ env.env_var }}
