name: deploy
on:
 workflow_call:
   inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
     
jobs:
  build:
    name: run the child pipline
    runs-on: ubuntu-latest
    steps:
     - name: run build ns
       run: |
         echo "Build the API from child"
         echo ${{ github.event.inputs.SP_USERNAME }}
         echo ${{ inputs.SP_USERNAME }}
         echo ${{ env.env_var }}
         echo ${{ image_name }}
         echo ${{ tag }}
        
